export CRON_BACKUP="0 8 * * *"
export CRON_ROTATE="59 23 * * *"
export CRON_DB_BACKUP="0 20 * * *"

export LOGS_DIRECTORY="/logs"
export LOGROTATE_POSTROTATE_COMMAND=""
export LOGROTATE_COPIES=3

export OBJECT_STORAGE_ACCESS_KEY=""
export OBJECT_STORAGE_SECRET_KEY=""
export OBJECT_STORAGE_BUCKET=""

export BROKER_URL=""
export VAULT_URL=""